### ISSUE TITLE
Should this library be merged into Avram?

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram_slugify#13]
It's just one file and doesn't provide a lot of functionality. Tried looking in the git commit history and the gitter room for some history on this decision but found nothing.

What if we moved this into Avram? So `AvramSlugify` would become `Avram::Slugify`, and we could make an alias for backwards compatibility.

**Comment by jwoertink** [comment]
wow... it was only added last year? 🤯  I'm sure Paul and I talked about it, but I can't remember. It felt like a few years ago. I think it would be fine. I can't see any reason why it would be better to be separated.
